package:
  name: pyptv
  version: 0.1.3

source:
  git_rev: '0.1.3'
  git_url: https://github.com/alexlib/pyptv.git

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # skip: True  # [py>27]
  # "skip: True  # [not win]" to limit to Windows.
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - numpy 
    - cython
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - scikit-image
    - chaco
    - enable

test:
  imports:
    - openptv
    - pyptv

about:
  home: https://github.com/alexlib/pyptv
  summary: Python GUI and the OpenPTV library `liboptv`
  license: MIT

