package:
  name: pyptv
  version: 0.1.3

source:
  git_rev: '0.1.3'
  git_url: https://github.com/alexlib/pyptv.git

requirements:
  build:
    - python
    - numpy 
    - cython
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - scikit-image
    - chaco
    - enable

test:
  imports:
    - openptv
    - pyptv

about:
  home: https://github.com/alexlib/pyptv
  summary: Python GUI and the OpenPTV library `liboptv`
  license: MIT

