# Config file for automatic testing at travis-ci.org

language: python
  - "2.7"
compiler:
  - clang
  - gcc
sudo: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake check build-essential git libgl1-mesa-glx libgl1-mesa-dev libglu1-mesa-dev
  - sudo apt-get clean
  - sudo apt-get autoclean
install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda install chaco cython scikit-image kiwisolver enable nose future pip
  - conda update numpy
  - conda update -q conda
  - conda clean --all
  - pip install --user coveralls
  - conda install conda-build
  - conda build .
  - conda install --use-local pyptv
  - sed -i 's/cbrt/#cbrt/' /opt/conda/lib/python2.7/site-packages/dask/array/ufunc.py
  - conda info -a
before_script:
  - hash -r 
  - export PATH=$HOME/lib:$/usr/local/lib:$PATH
  - export LD_LIBRARY_PATH=$HOME/lib:$/usr/local/lib:$LD_LIBRARY_PATH
  - ./install_openptv.sh
script:
  - export PATH=$PATH:/usr/local/lib
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib
  - echo $LD_LIBRARY_PATH
  - echo $PATH
  - python -c "import sys; print sys.path"
  - cd tests
  - nosetests -v
after_success:
  - coveralls
