# Config file for automatic testing at travis-ci.org

language: python
  - "3.7"
sudo: false
before_install:
  - apt-get -qq update
  - apt-get install -y build-essential 
  - apt-get install -y python python-pip python-setuptools python-dev python-virtualenv swig git
  - apt-get -y install python-qt4-gl libx11-dev g++ libpcre3 libpcre3-dev
  - apt-get -y install libgl1-mesa-glx libglu1-mesa-dev libgl1-mesa-dev mesa-common-dev freeglut3-dev libgtk2.0-dev
  - pip install numpy==1.16.1 cython nose pyyaml fonttools
  - pip install optv==0.2.4
  - pip install enable
  - pip install chaco
install:
  - cd pyptv/pyptv/ && pip install .
script:
  - cd tests
  - nosetests -v
after_success:
  - coveralls
