# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential 
  - sudo apt-get install -y python-dev swig
  - sudo apt-get -y install python-qt4-gl libx11-dev libpcre3 libpcre3-dev freeglut3-dev libgtk2.0-dev
  - sudo apt-get -y install libgl1-mesa-glx libglu1-mesa-dev libgl1-mesa-dev mesa-common-dev 
script:
  - python -m pip install -U pip
  - pip install -U wheel
  - pip install numpy
  - pip install pyptv --index-url https://pypi.fury.io/alexlib --extra-index-url https://pypi.org/simple
