# Config file for automatic testing at travis-ci.org

language: python
  - "2.7"
sudo: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential git libgl1-mesa-glx libgl1-mesa-dev libglu1-mesa-dev
  - sudo apt-get clean
  - sudo apt-get autoclean
install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda update -q conda
  - conda clean --all
  - pip install optv
  - pip install numpy cython swig chaco scikit-image enable nose future
  - pip install --user coveralls
  - conda install conda-build
  - conda build .
  - conda install --use-local pyptv
  - conda info -a
script:
  - cd tests
  - nosetests -v
after_success:
  - coveralls
