version: '3.7'

services:
  pyptv:
    build:
      context: .
      dockerfile: Dockerfile.tiredofit
    container_name: pyptv-novnc
    volumes:
      - ./data:/home/gui/work
    ports:
      - 3000:3000  # noVNC
    environment:
      - CONTAINER_NAME=pyptv-novnc
      - CONTAINER_PRETTY_NAME=PyPTV with noVNC
      - DESKTOP_TYPE=xfce
      - DEFAULT_TIMEZONE=Etc/UTC
      - DISPLAY_DEPTH=24
      - DISPLAY_HEIGHT=768
      - DISPLAY_WIDTH=1280
      - ENABLE_AUTHENTICATION=FALSE
      - ENABLE_GUACAMOLE=FALSE
      - ENABLE_NOVNC=TRUE
      - ENABLE_SSHD=FALSE
      - ENABLE_XVFB=TRUE
      - ENABLE_VNC=TRUE
      - ENABLE_XFCE_PANEL_PLUGINS=TRUE
      - ENABLE_XFCE_TERMINAL=TRUE
    restart: unless-stopped
    shm_size: '2gb'
