version: '3'

services:
  pyptv:
    build:
      context: .
      dockerfile: Dockerfile.novnc
    ports:
      - "6080:6080"  # noVNC web interface
      - "5901:5901"  # VNC port (optional, for direct VNC clients)
    volumes:
      - ./data:/home/pyptv/work  # Mount local data directory
    environment:
      - RESOLUTION=1280x720  # Lower resolution for better compatibility
    restart: unless-stopped
    shm_size: '2gb'  # Increase shared memory for X server
