version: '3'

services:
  pyptv:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    ports:
      - "3000:3000"  # noVNC web interface
    volumes:
      - ./data:/config/work  # Mount local data directory
    restart: unless-stopped
