package:
  name: pyptv
  version: 0.2.2

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # skip: True  # [py>27]
  # "skip: True  # [not win]" to limit to Windows.
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python=2.7
    - setuptools
  run:
    - python
    - numpy==1.10
    - scipy
    - cython
    - optv
    - pyyaml
    - chaco
    - enable
    - kiwisolver
    - future
    - scikit-image

about:
  home: https://github.com/alexlib/pyptv
  summary: Python GUI for the OpenPTV library `liboptv`
