package:
  name: pyptv
  version: 0.1.0

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  skip: True  # [py>27]
  skip: True  # [win]

requirements:
  build:
    - git 
    - cmake
  host:
    - python 2.7*
    - setuptools
    - cython
    - numpy
    - nose
    - pyyaml
  run:
    - python 2.7*
    - pyyaml
    - chaco
    - enable
    - kiwisolver
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - future
    - matplotlib
    - cython

# test:
#   imports:
#     - optv
#     - pyptv


about:
  home: https://github.com/alexlib/pyptv
  summary: Python GUI for the OpenPTV library `liboptv`
