package:
    name: pyptv
    version: 0.1.0
source:
  git_url: https://github.com/alexlib/pyptv.git
  git_tag: conda_build 
build:
    binary_relocation: false
    always_include_files:
      - pyptv/*.py
requirements:
    host:
      - python
      - numpy 1.10.2
      - scipy
      - matplotlib
      - kiwisolver
      - chaco
      - enable
      - future
      - pyyaml
      - openptv_c_lib
      - openptv_py_wrapper
    run:
        - chaco
        - cython
        - enable
        - future
        - kiwisolver
        - matplotlib
        - numpy
        - python
        - pyyaml
        - scikit-image
        - openptv_c_lib
        - openptv_py_wrapper
app:
  entry: python pyptv_gui.py
test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest tests
outputs:
  - name: pyptv
    files:
      - pyptv/*.py
about:
    home: https://github.com/alexlib/pyptv
    summary: Python GUI for the OpenPTV library `liboptv`
extra:
    copy_test_source_files: true
    final: true
