package:
  name: pyptv
  version: 0.1.0
source:
  # git_url: https://github.com/alexlib/pyptv.git
  # git_tag: conda_build 
  path: ..
build:
  binary_relocation: false
  always_include_files:
    - pyptv/*.py
  script:
    python setup.py install --single-version-externally-managed --record=record.txt
requirements:
  build:
    - python
  run:
    - python
    - chaco
    - cython
    - enable
    - future
    - kiwisolver
    - matplotlib
    - numpy
    - pyyaml
    - scikit-image
    - openptv_c_lib
    - openptv_py_wrapper
test:
  source_files:
    - tests
  requires:
    - pyptv
    - pytest
    - pytest-cov
  commands:
    - pytest tests
# outputs:
#   - name: pyptv
#     files:
#       - pyptv/*.py
about:
    home: https://github.com/alexlib/pyptv
    summary: Python GUI for the OpenPTV library `liboptv`
# extra:
#     copy_test_source_files: true
#     final: true
